---
packages_preinstall:
  - vim
  - bash-completion
  - wget
  - curl
  - yum-utils
  - lvm2
  - device-mapper-persistent-data
  - iproute-tc

docker:
  - docker-ce
  - docker-ce-cli
  - containerd.io

kube_tools:
  - kubeadm
  - kubelet
  - kubectl