---
packages_preinstall:
  - vim
  - bash-completion
  - wget
  - curl
  - firewalld
  - python3-firewall
  - yum-utils
  - lvm2
  - device-mapper-persistent-data
  - iproute-tc

docker:
  - docker-ce
  - docker-ce-cli
  - containerd.io

modprobe_kernel:
  - overlay
  - br_netfilter
  - ip_vs
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  - nf_conntrack

kube_tools:
  - kubeadm
  - kubelet
  - kubectl