---
# tasks file for ansible-install-k8s
- name: Configuraciones previas para instalar kubernetes.
  include_tasks: prerequisites.yaml

- name: Instalaci贸n de componentes y configuraci贸n del nodo master.
  include_tasks: master.yaml
  when: "'master' in group_names"

- name: Instalaci贸n de componentes y configuraci贸n del nodo worker.
  include_tasks: worker.yaml
  when: "'workers' in group_names"